version: 2
builds:
  - id: domwatch
    main: ./cmd/domwatch
    binary: domwatch
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
archives:
  - id: domwatch-archive
    builds: [domwatch]
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude: ['^docs:', '^test:', '^ci:']
